# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyPowerOf10' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyPowerOf10
  pod 'Kanna', :git => 'https://github.com/tid-kijyun/Kanna.git', :branch => 'feature/v4.0.0'
  pod 'TABResourceLoader', '~> 7.0.0'
	pod 'InteractiveSideMenu', '~> 2.1'

  target 'MyPowerOf10Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
