# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyPowerOf10' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyPowerOf10
  pod 'Kanna', '~> 2.0.0'
  pod 'TABResourceLoader', '~> 7.0.0'

  target 'MyPowerOf10Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
